version: 2.0

#
# Common components
#

common_steps: &common_steps
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        key: v1-deps-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
    - run:
        name: Install Dependencies
        command: pip install --user tox
    - run:
        name: Run Tests with Tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v1-deps-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}

common_env: &common_env
  TEST_DATABASE_BASE_URL: postgresql://root@127.0.0.1
  TEST_DATABASE_CI: circle_test

common_postgres: &common_postgres
  image: circleci/postgres:10-alpine
  environment:
    POSTGRES_USER: root
    POSTGRES_DB: circle_test
    POSTGRES_PASSWORD: ""

#
# Jobs
#

jobs:
  py37:
    <<: *common_steps
    docker:
      - image: circleci/python:3.7.0
        environment:
          <<: *common_env
          TOXENV: py37
      - <<: *common_postgres

#
# Workflows
#

workflows:
  version: 2
  test:
    jobs:
      - py37
